# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('screen_name', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=9, null=True)),
                ('utc_offset', models.IntegerField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=150, null=True)),
                ('geo_enabled', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('friends_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-time',),
                'verbose_name_plural': 'Profile history',
            },
        ),
    ]
