# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('friends_count', models.PositiveIntegerField(default=0)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('screen_name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'history',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('twitter_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('utc_offset', models.IntegerField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=150, null=True)),
                ('geo_enabled', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('friends_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
