# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileHistory',
        ),
        migrations.AlterModelOptions(
            name='profilehistory',
            options={'ordering': ('-time',), 'verbose_name_plural': 'Profile history'},
        ),
    ]
