# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50, unique=True)),
                ('hashtag', models.CharField(db_index=True, max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('ignore', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.URLField(db_index=True, unique=True)),
                ('expanded_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.URLField(db_index=True, unique=True)),
                ('expanded_url', models.URLField()),
                ('type', models.CharField(choices=[(b'p', b'photo'), (b'v', b'video')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=250)),
                ('truncated', models.BooleanField(default=False)),
                ('lang', models.CharField(blank=True, db_index=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('favorite_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('retweet_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('in_reply_to_status_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('in_reply_to_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('retweeted_status_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TweetHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(blank=True, db_index=True, max_length=9, null=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Hashtag')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(blank=True, db_index=True, max_length=9, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Keyword')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Link')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Media')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Symbol')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='tweetmention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.User'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_tweets', to='tweets.User'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtags',
            field=models.ManyToManyField(blank=True, through='tweets.TweetHashtag', to='tweets.Hashtag'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='keywords',
            field=models.ManyToManyField(blank=True, through='tweets.TweetKeyword', to='tweets.Keyword'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='media',
            field=models.ManyToManyField(blank=True, through='tweets.TweetMedia', to='tweets.Media'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_tweets', through='tweets.TweetMention', to='tweets.User'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='repost_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.ManyToManyField(blank=True, related_name='retweeted_tweets', to='tweets.User'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='symbols',
            field=models.ManyToManyField(blank=True, through='tweets.TweetSymbol', to='tweets.Symbol'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='urls',
            field=models.ManyToManyField(blank=True, through='tweets.TweetLink', to='tweets.Link'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.User'),
        ),
    ]
