# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_replica_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='favorite_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='lang',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweeted_status_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
