# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20160203_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
