# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_hashtag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
