# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('retry_after', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('access_level', models.PositiveSmallIntegerField(choices=[(1, 'Read only'), (2, 'Read and Write'), (3, 'Read, Write and Access direct messages')], default=2)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'OK'), (1, 'Restricted write access'), (2, 'Suspended')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RateLimitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('resource', models.CharField(max_length=100)),
                ('limit', models.PositiveIntegerField()),
                ('remaining', models.PositiveIntegerField()),
                ('reset', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.AccessToken')),
            ],
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.Application'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
