# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_auto_20160202_0629'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('retry_after', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='oauthtoken',
            name='application',
        ),
        migrations.RemoveField(
            model_name='oauthtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='type',
        ),
        migrations.AddField(
            model_name='application',
            name='access_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Read only'), (2, 'Read and Write'), (3, 'Read, Write and Access direct messages')], default=2),
        ),
        migrations.AlterField(
            model_name='ratelimitstatus',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.AccessToken'),
        ),
        migrations.DeleteModel(
            name='OAuthToken',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.Application'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
