# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.URLField(db_index=True, unique=True)),
                ('expanded_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.URLField(db_index=True, unique=True)),
                ('expanded_url', models.URLField()),
                ('type', models.CharField(choices=[(b'p', b'photo'), (b'v', b'video')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=250)),
                ('truncated', models.BooleanField(default=False)),
                ('lang', models.CharField(blank=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('retweet_count', models.PositiveIntegerField(default=0)),
                ('in_reply_to_status_id', models.BigIntegerField(blank=True, null=True)),
                ('in_reply_to_user_id', models.BigIntegerField(blank=True, null=True)),
                ('retweeted_status_id', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('hashtags', models.ManyToManyField(blank=True, to='tweets.Hashtag')),
                ('media', models.ManyToManyField(blank=True, to='tweets.Media')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_tweets', to='users.User')),
                ('symbols', models.ManyToManyField(blank=True, to='tweets.Symbol')),
                ('urls', models.ManyToManyField(blank=True, to='tweets.Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
