# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.URLField(db_index=True, unique=True)),
                ('expanded_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('type', models.CharField(choices=[(b'p', b'photo'), (b'v', b'video')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField()),
                ('text', models.CharField(max_length=250)),
                ('truncated', models.BooleanField(default=False)),
                ('lang', models.CharField(blank=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('retweet_count', models.PositiveIntegerField(default=0)),
                ('in_reply_to_status_id', models.BigIntegerField(blank=True, null=True)),
                ('in_reply_to_user_id', models.BigIntegerField(blank=True, null=True)),
                ('retweeted_status_id', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('user_screen_name', models.CharField(max_length=50)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TweetHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Hashtag')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtags',
            field=models.ManyToManyField(blank=True, through='tweets.TweetHashtag', to='tweets.Hashtag'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='media',
            field=models.ManyToManyField(blank=True, to='tweets.Media'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_tweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweet',
            name='symbols',
            field=models.ManyToManyField(blank=True, to='tweets.Symbol'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='urls',
            field=models.ManyToManyField(blank=True, to='tweets.Link'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
