# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('screen_names', models.TextField(blank=True, null=True)),
                ('user_ids', models.TextField(blank=True, editable=False, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('filter_level', models.CharField(blank=True, choices=[('l', 'low'), ('m', 'medium')], max_length=1, null=True)),
                ('tweets', models.ManyToManyField(blank=True, to='tweets.Tweet')),
            ],
        ),
    ]
