# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0001_initial'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screen_names', models.TextField(blank=True, null=True)),
                ('user_ids', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('filter_level', models.CharField(choices=[('n', 'none'), ('l', 'low'), ('m', 'medium')], default='n', max_length=1)),
                ('ignore_names', models.TextField(blank=True, null=True)),
                ('ignore_keywords', models.TextField(blank=True, null=True)),
                ('min_favorite_count', models.PositiveIntegerField(default=0)),
                ('min_retweet_count', models.PositiveIntegerField(default=0)),
                ('has_photo', models.NullBooleanField(default=None)),
                ('has_video', models.NullBooleanField(default=None)),
                ('has_hashtag', models.NullBooleanField(default=None)),
                ('has_mention', models.NullBooleanField(default=None)),
                ('has_symbol', models.NullBooleanField(default=None)),
                ('is_retweet', models.NullBooleanField(default=None)),
                ('is_reply', models.NullBooleanField(default=None)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.OAuthToken')),
                ('tweets', models.ManyToManyField(blank=True, to='tweets.Tweet')),
            ],
        ),
    ]
