# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='save_tweets',
            field=models.BooleanField(default=True),
        ),
    ]
