# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
