# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='owner',
        ),
    ]
