# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('l', 'Login'), ('s', 'Stream'), ('t', 'Tweet / Retweet'), ('f', 'Follow / Unfollow')], max_length=1, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'OK'), (1, 'Restricted write access'), (2, 'Suspended')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access_level', models.CharField(choices=[('r', 'Read only'), ('w', 'Read and Write'), ('m', 'Read, Write and Access direct messages')], default='w', max_length=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
