# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_auto_20160119_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Read only'), (2, 'Read and Write'), (3, 'Read, Write and Access direct messages')], default=2),
        ),
    ]
